Gesammelte Änderungen
FreiFunkMuenster/Ansible-Freifunk-Gateway pull request #108
Opened 2020-01-22 02:14 UTC by wusel42

Ein paar Erweiterungen der Rollen:

- BREAKING CHANGE: über ipv6backbone64prefixstr *muß* nun der interne v6-Präfix für Tunnel gesetzt werden — 2a03:2260:115:ffa1:: sollte nur FFMS nutzen.
- BREAKING CHANGE: Port 25 wird vom Mesh gen Internet blockiert.
- BREAKING CHANGE: Um 'zone "{{freifunk.kurzname}}."' weiterhin konfiguriert zu bekommen, muß "have_local_kurzname_zone" gesetzt werden. (Wir nutzen 4830.org als freifunk.kurzname, und damit erzeugt die Rolle eine falsche Version der öffentlichen Domain. Zudem tun "private" TLDs in aktuellen, insbesondere mobilen, Browsern eher so mäßig — mit DoH wird's auch haarig.)
-  ospf_nat_ip kann analog ff*_nat_ip verwendet werden, um diese IP im internen Routing per OSPF bekannt zu machen.
-  gateways_l2tp_slovenija nutzt letzten python2-kompatiblem commit vor der Änderung auf python3-only.
- Es gibt eine "FFGT-Version" des Mapservers, welche statt numerische Domains zu erzwingen mit normalen Textbezeichnern umgehen kann, ferner können dem Hopglass auch externe Quelle zugeführt werden.
- Bei ipv6_direkt_ausleiten wird ein zusätzlicher OSPF-Prozeß gestartet, der die lokalen Netze dem internen Routing bekannt macht, sodaß auch der Rückweg klappt.
- Kleinere Fixes.

2020-02-15 00:41 UTC, citronalco commented
Servus!
Bin zwar kein Münsteraner und weiß daher auch nicht, ob ich mich hier zu Wort melden soll, aber ich tu's einfach mal:

- Breaking Changes sind immer ungünstig. Dieses Repository dient ein paar anderen Communities als Grundlage, und nicht jeder liest alle Commit-Messages vor'm Ausrollen von Updates. So besteht die Gefahr dass sich Leute ihr Netz zerschießen. Wenn es sich einrichten lässt lasse den Standard so wie es ist und mache deine Änderung optional.
- Mach zu jedem Thema besser jeweils einen eigenen Pull Requests statt einem großen. Dann sieht man besser, was geändert wurde und kann schon Änderungen aufnehmen, obwohl vielleicht an einer anderen Stelle noch irgendwas nicht passt.
- Ich bin mir nicht sicher, ob das Pico Peering Agreement Portsperren zulässt. Ich war mit sicher, zu diesem Thema ausufernde Diskussionen im Freifunk-Forum zu finden. Eine schnelle Recherche hat jedoch nichts ergeben. Weißt du das was?
- Der Verzicht auf die {{freifunk.kurzname}}-Zone hört sich sehr interessant und erstrebenswert an. Gibt's dadurch irgendwelche Einschränkungen?

2020-02-15 17:13 UTC, wusel42 commented
> Bin zwar kein Münsteraner

Ich auch nicht.

> Breaking Changes sind immer ungünstig.

Bin ich völlig bei Dir; im Falle des v6-Prefixes, wo ein vom FFRL dem FFMS zugewiesener öffentlicher Adressraum festkodiert wurde, halte ich das für zwingend.

Was die restlichen beiden Punkte angeht, {{freifunk.kurzname}} hat das Potential, das Setup des Nutzers zu torpedieren (hat es bei uns), auch hier ist nur eine Variable zu setzen, um das alte Verhalten zu reaktivieren; ob man das nun als Opt-Out oder, wie hier, Opt-In implementiert, ist Geschmackssache, muß Münster  entscheiden, wie sie das bevorzugen. $Hier ist das kontraproduktiv, daher als Opt-In implementiert. 

Und Port 25 ausgehend zu sperren: das PPA hat mit zusätzlichen Diensten, wie hier dem Internetzugang, nichts zu tun. Und per IPv4 gibt es keinen legitimen Grund, Port 25 zu nutzen — 25 dient der MTA-MTA-Kommunikation (MUA-MTA ist 587), aber eingehend kann ein MTA im Mesh nichts empfangen (NAT). Bei public v6 sähe das anders aus, aus Gründen der Netzhygiene erscheint die Pflicht, ggf. einzelne v6-Adressen freizuschalten, besser, als im Nachhinein zu blocken.

> Mach zu jedem Thema besser jeweils einen eigenen Pull Requests statt einem großen. 

Das hält irgendwie jeder anders, $woanders wurde 1 PR mit vorzugsweise genau einem vollständigen Commit gewünscht. Aber to be honest: ich kann es nur so. (Und nein, ich habe für mehr als git {clone,pull,push,add,commit} keine Verwendung. Mag ja ein wundervoller Werkzeugkoffer sein; git als Rohrzange reicht mir.)

Um's kurz zu machen: ich bin dankbar für die Vorlage, und möchte gerne aus meiner Sicht sinnvolle Änderungen zurückgeben. Aber Ansible wie git sind für mich nur Nebenkriegsschauplätze; ich kann das nur auf works-for-me-Basis hinfrickeln, und PRs sind als Angebot zu verstehen, die Idee aufzugreifen. Schon das PR-en kostet mich viel zu viel Zeit (neu forken (zumal bei Gihub nur 1 Fork pro Account zulässig ist), Änderungen händisch applizieren, testen, PR machen); das selektive Nachziehen ist zwar auch scheiße, aber zumindest birgt das eine Erfolgsgarantie für mich.

> Macht ihr das mit der Knoten-IP über einen /etc/hosts-Eintrag auf dem Knoten oder löst ihr die dann auch über einen externen DNS auf?

Ich verstehe die Frage nicht? Welche IP welchen Knotens? Du meinst die nextnode-Geschichte?

Das hat bei uns keinen Namen (mehr), nachdem wir ffgt. ~2015 aufgegeben haben. thisnode.ffgt.net. gibt es noch, aber da wir lokal auch nicht mehr als Freifunk Gütersloh, sondern Freifunk Kreis GT, firmieren, wird das ebenfalls nicht mehr propagiert. Da wir seit ~2015 zudem eine FW nutzen, die für verschiedene Meshes funktioniert (Vorläufer von Multidomain, ähnlicher Ansatz, nur daß die gesamte site.conf ausgetauscht wurde anhand eines Location Codes), wurde nur noch die v4-IP je Mesh kommuniziert. Mit Multidomain droppen wir nun die nextnode-v4-Geschichte, und an sich ist der Plan, daß alle Meshes mit dem gleichen ULA-Prefix, fd10:ca1::/64, laufen — wir injezieren public v6 über die GWs, ULA ist also einzig im Mesh zweckmäßig. Dann gibt's ggf. irgendwann auch thisnode.4830.org, falls man sich fd10:ca1::1 nicht merken kann/will. Aber das gehört eigentlich eher ins Forum ;)

2020-02-17 18:42 UTC, MPW1412 commented
Hey Leute, wir gucken und das hier die Tage an. Ist gerade ein bisschen viel abseits von Freifunk. Vielen Dank für die eingereichten Vorschläge.

2020-02-19 23:54 UTC, MPW1412 requested changes
Moin,

vielen Dank für deinen PR! Das allermeiste finde ich super. Zu überlegen:

 - ffgt aus Rollenname entfernen
 - Adressraum aus bereits in Variable gespeichertem Präfix ableiten
 - Port 25 pauschal blocken wird so nicht aufgenommen. Bitte optionalisieren oder aus dem PR entfernen.

Wäre super, wenn wir das mergen könnten. Ist einiges sinnvolles dabei hier :)

2020-02-19 23:54 UTC, MPW1412 commented on backbone_gre_intern/templates/gre_interbackbone.j2
> -        address 2a03:2260:115:ffa1::{{hostvars[host].vm_id}}:{{vm_id}}:0
Könnte man das nicht vom Präfix dynamisch ableiten und dann einen festen vierten Block verwenden?

Ich finde es immer praktisch, möglichst viel dynamisch aus möglichst wenig Variablen zu generieren.

2020-02-19 23:54 UTC, MPW1412 commented on gateways_bind/templates/named.conf.ffnet.j2
> +{% if have_local_kurzname_zone is defined and have_local_kurzname_zone %}
Entweder sollten wir die Variablennamen deutsch oder englisch benennen. Das ist furchtbar so.

2020-02-19 23:54 UTC, MPW1412 commented on iptables/templates/rules.v4.j2
> +-A FORWARD -p tcp --dport 25 -j DROP
Das werden wir so pauschal nicht aufnehmen. Bitte konfigurierbar machen. Vorzugsweise direkt über eine Liste der zu sperrenden Ports.

Oder alternativ nur Port 25 über eine Variable „port_25_ausgehend_blocken“ oder ähnlich

2020-02-19 23:54 UTC, MPW1412 commented on iptables/templates/rules.v6.j2
> +-A FORWARD -p tcp --dport 25 -j DROP
Siehe oben.

2020-02-19 23:54 UTC, MPW1412 commented on mapserver_nginx_ffgt/handlers/main.yml
> +---
Warum ffgt im Namen? Würde ich rauslassen. Dieses Repo soll generisch für alle Communities sein.

2020-02-19 23:54 UTC, MPW1412 commented on mapserver_nginx_ffgt/tasks/main.yml
> +- name: install nginx
s. o. ffgt entfernen

2020-02-19 23:54 UTC, MPW1412 commented on mapserver_nginx_ffgt/templates/default.j2
> +server {
s. o. ffgt entfernen

2020-02-19 23:54 UTC, MPW1412 commented on mapserver_nginx_ffgt/templates/default_ssl.j2
> +server {
s. o. ffgt entfernen

2020-02-19 23:54 UTC, MPW1412 commented on mapserver_nginx_ffgt/templates/index.html.j2
> +<!DOCTYPE html>
s. o. ffgt entfernen

2020-02-19 23:54 UTC, MPW1412 commented on mapserver_nginx_ffgt/templates/tiles_cache.conf.j2
> +{% if 'cache_locations' in nginx_tiles_cache %}
s. o. ffgt entfernen

2020-02-20 14:42 UTC, wusel42 commented
Dunno, wie man 'nen PR ändert, typischerweise hört da meine Bereitschaft, Zeit zu investieren, auf.

Port 25 ist $hier nicht verhandelbar, da schon 2x v4 zu Recht auf RBL gelandet; restliche Argumentation s. o. Käme daher bei jedem PR wieder mit. Noch 'n Variable finde ich auch doof, wäre aber klar Option; dunno, wann ich dazu käme. Verstehe auch Euren Standpunkt, im Zweifel cherry-picken?

_ffgt: 'ne generische Rolle existiert schon, hab's nicht im Kopf, warum ich da was ändern wollte/mußte. Ah, wg. dem Namensgedöns, gut statt d01? Anyway, wenn das Eurerseits so ok ist, würde ich die alte durch die ffgt-Version ersetzen, _sollte_ nichts bei bestehenden Installationen kaputt gehen, aber nochmals drübergucken Eurerseits schadet sicher nicht :-)

> Entweder sollten wir die Variablennamen deutsch oder englisch benennen. Das ist furchtbar so.

Die Zone heißt IIRC kurzname, aber ja, der Name ist scheiße. Alternativvorschläge werden dankend angenommen — hätte am liebsten alles an/aus mit toggle_ oder so präfixt, aber dazu ist es auch schon zu spät.

V6-Präfix: den abzuleiten halte ich für ungünstig, denn damit definierst Du einen Bereich im /48 oder größer (/44 $hier), der im Netzplan ggf. anders verplant ist. Wir nutzen für Infra z. B. auch andern Block als für Mesh.

2020-02-20 19:19 UTC, MPW1412 commented
> Dunno, wie man 'nen PR ändert, typischerweise hört da meine Bereitschaft, Zeit zu investieren, auf.

Du kannst einfach weitere Commits in den zum PR gehörenden Zweig puschen, dann werden die automatisch angehängt.

> Port 25 ist $hier nicht verhandelbar, da schon 2x v4 zu Recht auf RBL gelandet; restliche Argumentation s. o. Käme daher bei jedem PR wieder mit. Noch 'n Variable finde ich auch doof, wäre aber klar Option; dunno, wann ich dazu käme. Verstehe auch Euren Standpunkt, im Zweifel cherry-picken?

Niemand hat gesagt, dass wir das nicht annehmen. Es muss nur per Variable im Ansible an- oder abschaltbar sein.

Sowas wie

{% if is defined block_port_25 and block_port_25 == true %}
<ip tables regel>
{% endif %}

> _ffgt: 'ne generische Rolle existiert schon, hab's nicht im Kopf, warum ich da was ändern wollte/mußte. Ah, wg. dem Namensgedöns, gut statt d01? Anyway, wenn das Eurerseits so ok ist, würde ich die alte durch die ffgt-Version ersetzen, _sollte_ nichts bei bestehenden Installationen kaputt gehen, aber nochmals drübergucken Eurerseits schadet sicher nicht :-)

Dann verstehe ich nicht, warum du die Rolle in den PR aufgenommen hast.
 
> V6-Präfix: den abzuleiten halte ich für ungünstig, denn damit definierst Du einen Bereich im /48 oder größer (/44 $hier), der im Netzplan ggf. anders verplant ist. Wir nutzen für Infra z. B. auch andern Block als für Mesh.

Ok, haben @HellMar und @RobWei hierzu eine Meinung? Von mir aus kann es auch so wie in deinem PR vorgeschlagen gemacht werden.

2020-02-20 19:39 UTC, HellMar commented
Port 25 Pauschal blocken find ich jetzt auch nicht so schön. Per Variable aktivierbar kein Problem. 

>Ok, haben @HellMar und @RobWei hierzu eine Meinung? Von mir aus kann es auch so wie in deinem PR vorgeschlagen gemacht werden.

Ich wäre für dynamisch...

2020-02-20 19:58 UTC, wusel42 commented
[Hmm, die Antwort per Mail von 18:29 ist wohl versackt. Daher als  paste:]

Moin,

> Port 25 pauschal blocken wird so nicht aufgenommen. Bitte optionalisieren oder aus dem PR entfernen.

dafür ist mir eine andere Lösung eingefallen (Liste von zu blockierenden Ports, getrennt nach UDP und TCP), war doch einfacher als gedacht. Der Mesh-Traffic kommt aus bat*, oder?

2020-02-20 20:38 UTC, RobWei commented
> dafür ist mir eine andere Lösung eingefallen (Liste von zu blockierenden Ports, getrennt nach UDP und TCP), war doch einfacher als gedacht.

Mit der Lösung hätte ich kein Problem.

> Der Mesh-Traffic kommt aus bat*, oder?

B.A.T.M.A.N Traffic findet man im br*-Interface
IP Traffic findest du in im bat*-Interface

2020-02-20 22:18 UTC, HellMar commented
>>dafür ist mir eine andere Lösung eingefallen (Liste von zu blockierenden Ports, getrennt nach UDP und TCP), war doch einfacher als gedacht.

>Mit der Lösung hätte ich kein Problem.

Dito.

2020-02-21 03:49 UTC, wusel42 commented
Es ist wie es ist: intern ist die Karavane weitergezogen (anderer Fork), das nach einem Monat zusammenzuführen ist mir zu aufwendig. Ihr könnt hieraus cherry-picken und Euch https://github.com/wusel42/PR20200220/commit/6fc6e4817940490ecf741b11cc3014719198c515 ansehen, mehr kann ich nicht leisten.

2020-02-21 03:49 UTC, closed without merging

2020-02-25 20:27 UTC, MPW1412 commented
> , das nach einem Monat zusammenzuführen ist mir zu aufwendig. Ihr könnt hieraus cherry-picken und Euch [wusel42/PR20200220@6fc6e48](https://github.com/wusel42/PR20200220/commit/6fc6e4817940490ecf741b11cc3014719198c515) ansehen, mehr kann ich nicht leisten.

Ganz ehrlich, ist leiste mir auch mal was: Ein bisschen Ehrlichkeit. 

Du stellst hier 'nen beschiss..eiden strukturierten PR rein, der Breaking Changes enthält, die man leicht hätte vermeiden können und mehrere Features in einem, obwohl man genau das nicht macht. Dann machen sich mehrere Leute die Mühe das Chaos zu durchforsten und du schließt ihn einfach. Danke für nichts.

Meinst du wir finden das toll auf Extrawünsche anderer Communities einzugehen? Wir machen es halt, weil es sinnvoll ist. So läuft Software-Entwicklung nunmal.

Wenn du einfach deinen Kram durchziehst, divergiert es doch nur noch weiter. Aber viel Spaß damit 😀