motd: Kleinere Fixes
FreiFunkMuenster/Ansible-Freifunk-Gateway pull request #86
Opened 2019-10-06 09:12 UTC by citronalco

- motd benötigt zur Anzeige der Betriebssystemversion das Paket "lsb-release".
- Bei jedem Ansibledurchlauf wurde der Task "figlet-name" als "changed" berichtet obwohl dieser Task nie etwas auf dem Host ändert (das passiert ein paar Tasks später)
- Die Message war komplett auf Englisch, bis auf "Besitzer". Habe das durch "Owner" ersetzt.

2019-10-06 14:04 UTC, MPW1412 commented on motd/templates/99-custom.j2
> +echo " Owner       : {{ server_besitzer }}"
Wir haben bisher alle Variablen und Kommentare auf Deutsch.

2019-10-06 14:05 UTC, MPW1412 requested changes
Die Änderung in 99-custom.j2 würde ich nicht übernehmen wollen.

2019-10-06 18:34 UTC, citronalco commented
OK, daran soll's nicht scheitern: "Owner" heißt wieder "Besitzer".

2019-10-06 18:54 UTC, HellMar commented
Naja ich mein er hat ja schon nicht ganz unrecht. IP Address, System type etc müssten dann konsequenterweise auch Deutsch werden.

2019-10-11 07:18 UTC, MPW1412 approved these changes

2019-10-11 08:22 UTC, merged